name: Main

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**/README.md"
      - "assets/**"

jobs:
  demo-debug:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
      - name: "Setup Java 17"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Assemble Debug"
        run: ./gradlew :demo:assembleDebug --no-daemon
      - name: "Upload Debug APK to GitHub"
        uses: actions/upload-artifact@v3
        with:
          name: Debug APK
          path: demo/build/outputs/apk/debug/demo-debug.apk
  seattle-debug:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
      - name: "Setup Java 17"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Assemble Debug"
        run: ./gradlew :seattle:assembleDebug --no-daemon
      - name: "Upload Debug APK to GitHub"
        uses: actions/upload-artifact@v3
        with:
          name: Debug APK
          path: demo/build/outputs/apk/debug/seattle-debug.apk
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
      - name: "Setup Java 17"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Lint"
        run: ./gradlew lint --no-daemon
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
      - name: "Setup Java 17"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Test"
        run: ./gradlew test --no-daemon
  maestro-test:
    runs-on: macos-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
      - name: "Setup Java 17"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: "Install Maestro"
        uses: dniHze/maestro-test-action@v1
      - name: Run Maestro test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          script: meaestro test --format=junit --output=report.xml --no-ansi maestro.yml
  demo-release-sign-publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
      - name: "Setup Java 17"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Generate Release AAB"
        run: ./gradlew :demo:bundleRelease --no-daemon
      - name: "Sign Android release"
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: demo/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "33.0.2"
      - name: "Upload Release AAB to GitHub"
        uses: actions/upload-artifact@v3
        with:
          name: Release AAB
          path: demo/build/outputs/bundle/release/demo-release.aab
      - name: "Upload Release AAB to Play Store"
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.louis993546.metro.demo
          releaseFiles: demo/build/outputs/bundle/release/demo-release.aab
          track: beta
          status: completed
  seattle-release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
      - name: "Setup Java 17"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Generate Release AAB"
        run: ./gradlew :seattle:bundleRelease --no-daemon
#      - name: "Sign Android release"
#        uses: r0adkll/sign-android-release@v1
#        with:
#          releaseDirectory: seattle/build/outputs/bundle/release
#          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
#          alias: ${{ secrets.ALIAS }}
#          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
#          keyPassword: ${{ secrets.KEY_PASSWORD }}
#      - name: "Upload Release AAB to GitHub"
#        uses: actions/upload-artifact@v3
#        with:
#          name: Release AAB
#          path: seattle/build/outputs/bundle/release/seattle-release.aab
#      - name: "Upload Release AAB to Play Store"
#        uses: r0adkll/upload-google-play@v1
#        with:
#          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
#          packageName: com.louis993546.metro.seattle
#          releaseFiles: seattle/build/outputs/bundle/release/seattle-release.aab
#          track: beta
#          status: completed
#        env:
#          BUILD_TOOLS_VERSION: "33.0.2"
  lib-api-check:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
      - name: "Setup Java 17"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Check API"
        run: ./gradlew :metro:apiCheck --no-daemon
  publish-lib:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
      - name: "Setup Java 17"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Publish package"
        run: ./gradlew publish --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
